name: Run test

on: 
  # workflow_dispatch enables manual trigger
  workflow_dispatch

  # Runs on pushes targeting the default branch
  # push:
  #   branches: ["main"]
  # # Ignore changes in folders that are affected by the auto commit.
  #   paths-ignore: 
  #     - 'results/**'

jobs:
  run-benchmark:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4
      - name: Run test script
        run: ./runtest.sh
